version: 0.2

phases:
  install:
  commands:
    - yum update -y
    - amazon-linux-extras enable nginx1
    - yum install -y nginx


  build:
    commands:
      - echo Build started on `date`
      - mkdir -p output
      - cp index.html output/

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - output/index.html


 


 


# version: 0.2

# phases:
#   install:
#     commands:
#       - echo "Install phase started"
#   build:
#     commands:
#       - echo "Build phase started - no build needed for static site"

# artifacts:
#   files:
#     - '**/*'
